///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace HansenTechnology
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the HansenTechnologyRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("3141e777-92dc-4cba-a392-ba9767820573")]
    public partial class HansenTechnologyRepository : RepoGenBaseFolder
    {
        static HansenTechnologyRepository instance = new HansenTechnologyRepository();
        HansenTechnologyRepositoryFolders.RxMainFrameAppFolder _rxmainframe;

        /// <summary>
        /// Gets the singleton class instance representing the HansenTechnologyRepository element repository.
        /// </summary>
        [RepositoryFolder("3141e777-92dc-4cba-a392-ba9767820573")]
        public static HansenTechnologyRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public HansenTechnologyRepository() 
            : base("HansenTechnologyRepository", "/", null, 0, false, "3141e777-92dc-4cba-a392-ba9767820573", ".\\RepositoryImages\\HansenTechnologyRepository3141e777.rximgres")
        {
            _rxmainframe = new HansenTechnologyRepositoryFolders.RxMainFrameAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("3141e777-92dc-4cba-a392-ba9767820573")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("1a393b43-d56a-4330-ae21-be8046401f63")]
        public virtual HansenTechnologyRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class HansenTechnologyRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("1a393b43-d56a-4330-ae21-be8046401f63")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _enteryournameInfo;
            RepoItemInfo _btnsubmitusernameInfo;
            RepoItemInfo _lblwelcomemessageInfo;
            RepoItemInfo _resetInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "1a393b43-d56a-4330-ae21-be8046401f63", "")
            {
                _enteryournameInfo = new RepoItemInfo(this, "EnterYourName", "?/?/tabpage[@controlname='RxTabIntroduction']/?/?/text[@accessiblename='Enter your name']", 30000, null, "53458ee4-6bcd-4014-a593-4fa88860b2ae");
                _btnsubmitusernameInfo = new RepoItemInfo(this, "BtnSubmitUserName", "?/?/tabpage[@controlname='RxTabIntroduction']/button[@controlname='btnSubmitUserName']", 30000, null, "16c744f9-0349-4c91-bdd9-237762b9e46a");
                _lblwelcomemessageInfo = new RepoItemInfo(this, "LblWelcomeMessage", "?/?/tabpage[@controlname='RxTabIntroduction']/text[@controlname='lblWelcomeMessage']", 30000, null, "80ea1b4f-d3bc-48ba-bc31-3f3504ab5200");
                _resetInfo = new RepoItemInfo(this, "Reset", "?/?/tabpage[@controlname='RxTabIntroduction']/link[@controlname='RxLinkBtnReset']/?/?/link[@accessiblename='Reset']", 30000, null, "f749b6cd-ffd4-48d1-90fb-a827ccbd2be7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1a393b43-d56a-4330-ae21-be8046401f63")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1a393b43-d56a-4330-ae21-be8046401f63")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EnterYourName item.
            /// </summary>
            [RepositoryItem("53458ee4-6bcd-4014-a593-4fa88860b2ae")]
            public virtual Ranorex.Text EnterYourName
            {
                get
                {
                    return _enteryournameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EnterYourName item info.
            /// </summary>
            [RepositoryItemInfo("53458ee4-6bcd-4014-a593-4fa88860b2ae")]
            public virtual RepoItemInfo EnterYourNameInfo
            {
                get
                {
                    return _enteryournameInfo;
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item.
            /// </summary>
            [RepositoryItem("16c744f9-0349-4c91-bdd9-237762b9e46a")]
            public virtual Ranorex.Button BtnSubmitUserName
            {
                get
                {
                    return _btnsubmitusernameInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item info.
            /// </summary>
            [RepositoryItemInfo("16c744f9-0349-4c91-bdd9-237762b9e46a")]
            public virtual RepoItemInfo BtnSubmitUserNameInfo
            {
                get
                {
                    return _btnsubmitusernameInfo;
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item.
            /// </summary>
            [RepositoryItem("80ea1b4f-d3bc-48ba-bc31-3f3504ab5200")]
            public virtual Ranorex.Text LblWelcomeMessage
            {
                get
                {
                    return _lblwelcomemessageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item info.
            /// </summary>
            [RepositoryItemInfo("80ea1b4f-d3bc-48ba-bc31-3f3504ab5200")]
            public virtual RepoItemInfo LblWelcomeMessageInfo
            {
                get
                {
                    return _lblwelcomemessageInfo;
                }
            }

            /// <summary>
            /// The Reset item.
            /// </summary>
            [RepositoryItem("f749b6cd-ffd4-48d1-90fb-a827ccbd2be7")]
            public virtual Ranorex.Link Reset
            {
                get
                {
                    return _resetInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The Reset item info.
            /// </summary>
            [RepositoryItemInfo("f749b6cd-ffd4-48d1-90fb-a827ccbd2be7")]
            public virtual RepoItemInfo ResetInfo
            {
                get
                {
                    return _resetInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
